### PR TITLE
populating the precip and radiation fluxes in Atmos data structure by default

### PR DESCRIPTION
**Pull request by gaokun227**
This change will populate the precipitation and radiation fluxes in the Atmos data structure by default once they are updated  by the SHiELD physics.

The `fullcoupler_fluxes` namelist parameter will now cleanly control whether the coupled SHiELD-MOM6 model operates in two-way or one-way coupling mode.

- **True**: SHiELD and MOM6 are two-way coupled. SHiELD is forced with air-sea fluxes from the full coupler.
- **False**: SHiELD and MOM6 are one-way coupled. SHiELD does not receive air-sea fluxes from the full coupler, but still provides surface precipitation and radiation fluxes to MOM6 via the coupler.

### CODE REVIEW

**Comment by gaokun227** [comment]
@laurenchilutti hi Lauren, could you add Joseph as a reviewer? Thanks!

**Comment by JosephMouallem** [comment]
looks good to me, thanks!

**Comment by gaokun227** [comment]
@laurenchilutti please consider merge this MR if there are no more comments. We have downstream users waiting for the code update.

**Review by uramirez8707 — APPROVED** [review]

**Review by laurenchilutti — APPROVED** [review]

**Comment by laurenchilutti** [comment]
@gaokun227 Thank you for pinging me on this.  I was waiting on reviewers but I see Joseph has approved.

**Pull request merged**
