### PR TITLE
Add driver to run SHiELD (and SHiEMOM) with the full FMS coupler

### PR DESCRIPTION
**Pull request by JosephMouallem**
Add files under /SHiELDFULL/ to compile and run SHiELD with the full FMS coupler.

The same files allow running the new model SHiEMOM (SHiELD+MOM6) as well. 
The user should set fullcoupler_fluxes=.true. in the namelist atmos_model_nml to apply the fluxes (computed on the exchange grid in the full coupler) back on the atmosphere. 

Tested on Gaea, Stellar and Orion.
(On Orion before the latest big environment update)

**Checklist:**
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included

### CODE REVIEW

**Review by lharris4 — APPROVED** [review]
Looks fine to me. A couple of questions:

- Are the new files principally to replicate functionality needed by the coupler that exists in AM4 but not in SHiELD?
- Can we can now use the tracer_driver (ie. AM4 aerosols and chemistry) within SHiELD? I see that the tracer_driver routines are principally stubs and don't do anything.

**Comment by JosephMouallem** [comment]
Hi Lucas, yes true.
I added all these files, which are taken from atmos_null, to compile the full coupler and satisfy its dependencies.
I think since we already have the routines here, we could probably take advantage of their functionality.

**Review by laurenchilutti — APPROVED** [review]

**Review by bensonr — COMMENTED** [review]
Did the atmos_tracer_driver.html come from the repo you branched off?  Or did you write this file yourself?

**Comment by JosephMouallem** [comment]
It comes from NOAA-GFDL/atmos_null:
https://github.com/NOAA-GFDL/atmos_null

**Comment by bensonr** [comment]
I think we can safely remove it as we tend to keep zero html files around anymore

**Review by laurenchilutti — APPROVED** [review]

**Review by bensonr — APPROVED** [review]

**Review by uramirez8707 — APPROVED** [review]

**Review by thomas-robinson — COMMENTED** [review]
@JosephMouallem These updates needlessly clutter the atmos driver which is a fairly simple repo to only run the atmosphere.  The code is mostly copy and paste from physics, so I think these updates should go in the physics.  

The code does not follow the style guidelines, especially the documentation part about using doxygen style including descriptions for all routines and modules
https://github.com/NOAA-GFDL/atmos_drivers/blob/main/CODE_STYLE.md

**Comment by JosephMouallem** [comment]
@thomas-robinson Thanks for your feedback, we can certainly move the extra files out of SHiELDFULL/ and only leave atmos_model.F90.

We could place them under SHiELD_physics/atmos_shared/ similar to what is done in NOAA-GFDL/atmos_phys.
@lharris4, @bensonr how does this sound?

**Comment by lharris4** [comment]
@JosephMouallem @thomas-robinson I think `SHiELD_physics/atmos_shared/` is the best place as it follows the construction of the [AM4 Physics](https://github.com/NOAA-GFDL/atmos_phys). In theory we could use this to bring in aerosol and chemistry routines from AM4 to SHiELD.

**Comment by JosephMouallem** [comment]
@thomas-robinson The extra atmos files were removed and added to SHiELD_physics. Description of variables and subroutines is revised and now follows the code style of other atmos_model.F90 under coupled/ and SHiELD/

**Review by thomas-robinson — APPROVED** [review]
ok.  I set up https://github.com/NOAA-GFDL/atmos_drivers/issues/42 related to updating the comment/documentation in this repo.

**Pull request merged**
