### PR TITLE
Enable outputting surface type fraction diagnostics from SHiELD

### PR DESCRIPTION
**Pull request by spencerkclark**
**Description**

This small PR is required for compatibility with NOAA-GFDL/SHiELD_physics#36.  See the PR description there for more details regarding what this is for and how it was tested.

**Checklist:**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] New check tests, if applicable, are included

### CODE REVIEW

**Review by lharris4 — APPROVED** [review]
Approved. It may be good if we could have a more generic interface to the SHiELD physics diagnostics so that we don't need to update the driver every time there is a change to the function calls.

**Review by laurenchilutti — APPROVED** [review]

**Comment by spencerkclark** [comment]
Thanks @laurenchilutti!

**Comment by bensonr** [comment]
> Approved. It may be good if we could have a more generic interface to the SHiELD physics diagnostics so that we don't need to update the driver every time there is a change to the function calls.

@lharris4 - after a quick look at the gfdl controlled diag function, I believe the existing framework could've been adapted to handle the use case.  The one change  to keep from having to update the atmos_driver would be to include the whole IPD_Control data structure to the existing interface instead of updating it for each new control variable you want to pass.  This change allows the existing interface, which contains all of the needed physics data elements, to handle changes down in the functional layers - though it's too late to change it now.

**Comment by lharris4** [comment]
Hi, Rusty. Indeed it is better to pass the whole structure rather than individual sub-elements. Ideally all of the interfaces to the Physics Driver would pass all of the relevant structures so we don't need to update both codes when we need a data element inside a different structure.

**Comment by bensonr** [comment]
The physics driver currently passes everything and we could actually update the IPD interface used in SHiELD to have only two interfaces and rely on function pointers within the atmos_driver routines.  It is a handful of the initialization routines that don't use everything that precipitates changes each time we want to add something.

**Pull request merged**
